/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/debug`; params?: Router.UnknownInputParams; } | { pathname: `/planning`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/concept`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/planning`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/pseudo`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/splash`; params?: Router.UnknownInputParams; } | { pathname: `/session/new`; params?: Router.UnknownInputParams; } | { pathname: `/session/share`; params?: Router.UnknownInputParams; } | { pathname: `/session/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/debug`; params?: Router.UnknownOutputParams; } | { pathname: `/planning`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/sessions`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/concept`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/planning`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/pseudo`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/session/new`; params?: Router.UnknownOutputParams; } | { pathname: `/session/share`; params?: Router.UnknownOutputParams; } | { pathname: `/session/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/debug${`?${string}` | `#${string}` | ''}` | `/planning${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/sessions${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | `/onboarding/concept${`?${string}` | `#${string}` | ''}` | `/onboarding/planning${`?${string}` | `#${string}` | ''}` | `/onboarding/pseudo${`?${string}` | `#${string}` | ''}` | `/onboarding/splash${`?${string}` | `#${string}` | ''}` | `/session/new${`?${string}` | `#${string}` | ''}` | `/session/share${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/debug`; params?: Router.UnknownInputParams; } | { pathname: `/planning`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/concept`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/planning`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/pseudo`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/splash`; params?: Router.UnknownInputParams; } | { pathname: `/session/new`; params?: Router.UnknownInputParams; } | { pathname: `/session/share`; params?: Router.UnknownInputParams; } | `/session/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/session/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
